// Generated by scripts/generate-logo.mjs with Chafa 1.18.2. Do not hand-edit.
export interface LogoSegment { readonly text: string; readonly color?: string }
export const LOGO_LINES: readonly (readonly LogoSegment[])[] = [
  [
    {
      "text": "                    "
    },
    {
      "text": "_",
      "color": "#9FB0FF"
    }
  ],
  [
    {
      "text": "      "
    },
    {
      "text": "_",
      "color": "#6784FF"
    },
    {
      "text": "ygggggg@B",
      "color": "#4C6AFF"
    },
    {
      "text": "   "
    },
    {
      "text": "u",
      "color": "#9FB0FF"
    },
    {
      "text": "@y",
      "color": "#4C6AFF"
    },
    {
      "text": "_",
      "color": "#6784FF"
    },
    {
      "text": "   "
    },
    {
      "text": "_",
      "color": "#6784FF"
    },
    {
      "text": "y",
      "color": "#4C6AFF"
    }
  ],
  [
    {
      "text": "    "
    },
    {
      "text": "y",
      "color": "#9FB0FF"
    },
    {
      "text": "g@@@@@@@@@@g",
      "color": "#4C6AFF"
    },
    {
      "text": "y",
      "color": "#6784FF"
    },
    {
      "text": "  "
    },
    {
      "text": "@@@g@@@",
      "color": "#4C6AFF"
    },
    {
      "text": "M",
      "color": "#6784FF"
    }
  ],
  [
    {
      "text": "   "
    },
    {
      "text": "y",
      "color": "#9FB0FF"
    },
    {
      "text": "@@@@@@@@@@@@@@$y",
      "color": "#4C6AFF"
    },
    {
      "text": "`",
      "color": "#9FB0FF"
    },
    {
      "text": "5@@AM~",
      "color": "#4C6AFF"
    }
  ],
  [
    {
      "text": "   "
    },
    {
      "text": "$@",
      "color": "#4C6AFF"
    },
    {
      "text": "   "
    },
    {
      "text": "`",
      "color": "#9FB0FF"
    },
    {
      "text": "~?@@@@@",
      "color": "#4C6AFF"
    },
    {
      "text": "W",
      "color": "#6784FF"
    },
    {
      "text": "7R@@@@@",
      "color": "#4C6AFF"
    }
  ],
  [
    {
      "text": "   "
    },
    {
      "text": "4@y",
      "color": "#4C6AFF"
    },
    {
      "text": "      "
    },
    {
      "text": "~",
      "color": "#6784FF"
    },
    {
      "text": "R@@@W",
      "color": "#4C6AFF"
    },
    {
      "text": "y",
      "color": "#6784FF"
    },
    {
      "text": "2@@@^",
      "color": "#4C6AFF"
    }
  ],
  [
    {
      "text": "    "
    },
    {
      "text": "@@g",
      "color": "#4C6AFF"
    },
    {
      "text": "       "
    },
    {
      "text": "7@@@@@@@~",
      "color": "#4C6AFF"
    }
  ],
  [
    {
      "text": "     "
    },
    {
      "text": "M@@y",
      "color": "#4C6AFF"
    },
    {
      "text": "_",
      "color": "#6784FF"
    },
    {
      "text": " "
    },
    {
      "text": "4@g_",
      "color": "#4C6AFF"
    },
    {
      "text": " "
    },
    {
      "text": "5@@@@_",
      "color": "#4C6AFF"
    }
  ],
  [
    {
      "text": "      "
    },
    {
      "text": "`",
      "color": "#9FB0FF"
    },
    {
      "text": "7R@@@@@@@$mTFFF~",
      "color": "#4C6AFF"
    }
  ],
  [
    {
      "text": "           "
    },
    {
      "text": "~TT~",
      "color": "#6784FF"
    }
  ]
]
export const MONO_LOGO_LINES: readonly string[] = [
  "",
  "",
  "                    _",
  "      _yygggag@F    @y_   __",
  "    _g@@@@@@@@@@g_  @@@g@@@F",
  "   _@@@@@@@@@@@@@@$y`5@@PF~",
  "   $@    ~~@@@@@W~4@@@@$",
  "   4@L      ~R@@@y_2@@@^",
  "    @@y       ~@@@@@@@~",
  "     4@@y_ 4@y_ 4@@@E_",
  "      `~R@@@@@@@a=~FFF~",
  "          `~~~~`",
  "",
  ""
]
