import { createHash } from 'node:crypto'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { spawnSync } from 'node:child_process'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const image = join(root, 'assets', 'reference', 'deepseek-github-avatar.png')
const outputPath = join(root, 'src', 'ui', 'logo.generated.ts')
const candidates = process.platform === 'win32'
  ? [join(root, '.m1-tools', 'chafa', 'chafa-1.18.2-1-x86_64-win', 'Chafa.exe')]
  : ['chafa']
const chafa = candidates.find(existsSync) ?? candidates[0]
const expectedImageSha256 = '55e6e0c1ba0c453749211368b8a26e00f470b4ab696ce1fed539d70777d4aab1'

const actual = createHash('sha256').update(readFileSync(image)).digest('hex')
if (actual !== expectedImageSha256) throw new Error(`DeepSeek logo SHA-256 mismatch: ${actual}`)

// The generated logo ships with the repository. Chafa is only needed to
// regenerate it locally (e.g. after replacing the reference image), so a
// build without Chafa — CI runners — keeps the checked-in artifact as-is.
if (!candidates.some(existsSync) && existsSync(outputPath)) {
  console.log('Chafa not found; keeping the checked-in src/ui/logo.generated.ts')
  process.exit(0)
}

const common = ['--format', 'symbols', '--probe', 'off', '--relative', 'off', '--animate', 'off', '--size', '30x14', '--stretch', '--fg-only', '--invert', '--symbols', 'ascii', '--color-extractor', 'median', '--dither', 'none']
function run(args) {
  const result = spawnSync(chafa, [...common, ...args, image], { encoding: 'utf8', env: { ...process.env, TERM: 'xterm-truecolor' } })
  if (result.status !== 0) throw new Error(result.stderr || `Chafa exited ${result.status}`)
  return result.stdout.replaceAll('\r', '')
}

function coloredLines(ansi) {
  let color
  const lines = [[]]
  for (let i = 0; i < ansi.length;) {
    if (ansi[i] === '\u001b') {
      const match = /^\u001b\[([0-9;?]*)([A-Za-z])/.exec(ansi.slice(i))
      if (match) {
        if (match[2] === 'm') {
          const code = match[1]
          const rgb = /^38;2;(\d+);(\d+);(\d+)$/.exec(code)
          if (rgb) color = rgb.slice(1).map(Number)
          else if (code === '39' || code === '0') color = undefined
        }
        i += match[0].length
        continue
      }
    }
    const char = ansi[i++]
    if (char === '\n') { lines.push([]); continue }
    const white = color === undefined || color.every(channel => channel >= 225)
    const text = white ? ' ' : char
    const quantized = white ? undefined : color[0] < 90 ? '#4C6AFF' : color[0] < 150 ? '#6784FF' : '#9FB0FF'
    const line = lines.at(-1)
    const previous = line.at(-1)
    if (previous !== undefined && previous.color === quantized) previous.text += text
    else line.push({ text, ...(quantized === undefined ? {} : { color: quantized }) })
  }
  return lines.filter(line => line.length > 0).map(line => {
    while (line.at(-1) !== undefined && line.at(-1).color === undefined) line.pop()
    return line
  }).filter(line => line.length > 0)
}

const color = coloredLines(run(['--colors', 'full']))
const mono = run(['--colors', 'none']).split('\n').filter(Boolean).map(line => line.trimEnd())
const source = `// Generated by scripts/generate-logo.mjs with Chafa 1.18.2. Do not hand-edit.\n` +
  `export interface LogoSegment { readonly text: string; readonly color?: string }\n` +
  `export const LOGO_LINES: readonly (readonly LogoSegment[])[] = ${JSON.stringify(color, null, 2)}\n` +
  `export const MONO_LOGO_LINES: readonly string[] = ${JSON.stringify(mono, null, 2)}\n`
writeFileSync(join(root, 'src', 'ui', 'logo.generated.ts'), source)
